export default  {
    products: [
        {
            _id: '1',
            name: 'Hemp Seed Body Oils Set',
            image: './images/prod-1.jpg',
            price: 45.99,
            brand: 'Erbology',
            rating: 3.6,
            numReviews: 14867,
            countInStock: 1234,
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        },
        {
            _id: '2',
            name: 'Softening Eye Cream',
            image: './images/prod-2.jpg',
            price: 13.33,
            brand: 'Some Brand',
            rating: 4.6,
            numReviews: 1086,
            countInStock: 0,
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        },
        {
            _id: '3',
            name: 'Body Lotion',
            image: './images/prod-3.jpg',
            price: 9.99,
            brand: 'Some Brand',
            rating: 3,
            numReviews: 1086,
            countInStock: 1548,
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        },
        {
            _id: '4',
            name: 'Premium CBD Oil',
            image: './images/prod-4.jpg',
            price: 43.88,
            brand: 'Premium Brand',
            rating: 4.8,
            numReviews: 1230945,
            countInStock: 1532,
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        },
        {
            _id: '5',
            name: 'Mini Body Lotion',
            image: './images/prod-5.jpg',
            price: 19.99,
            brand: 'Necessaire',
            rating: 2.6,
            numReviews: 214390,
            countInStock: 3242,
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        },
        {
            _id: '6',
            name: 'Hydrating Lotion Set',
            image: './images/prod-6.jpg',
            price: 63.99,
            brand: 'La Roche',
            rating: 5,
            numReviews: 12343,
            countInStock: 2353,
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        },
        {
            _id: '7',
            name: 'Facial Moisturizer Set',
            image: './images/prod-7.jpg',
            price: 15.99,
            brand: 'The Ordinary',
            rating: 3.6,
            numReviews: 1086,
            countInStock: 1548,
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        },
        {
            _id: '8',
            name: 'Rose Seed Oil',
            image: './images/prod-8.jpg',
            price: 15.33,
            brand: 'Some Brand',
            rating: 2.6,
            numReviews: 1086,
            countInStock: 2453,
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        }
    ]
};